### ISSUE TITLE
ModuleNotFoundError: No module named 'windows_auth'

### ISSUE THREAD

**Issue by RohanIRathi** [danyi1212/django-windowsauth#2]
Hi,
    I followed the guide provided [over here](https://django-windowsauth.readthedocs.io/en/latest/installation/installation.html), but I am getting ModuleNotFoundError for "windows_auth" which I add in the INSTALLED_APPS list when I run the command `python3 manage.py migrate windows_auth`

**Comment by danyi1212** [comment]
You are correct, there was an incorrect configuration for the PyPI Packaging.

I've just released a new version 1.3.1 with a fix.
